apiVersion: v1
kind: Service
metadata:
  name: frontend-lb
spec:
  ports:
  # Порт сетевого балансировщика, на котором будут обслуживаться пользовательские запросы.
  - port: 443
    name: plaintext
    # Порт контейнера, на котором доступно приложение.
    targetPort: 443
  # Метки селектора, использованные в шаблоне подов при создании объекта Deployment.
  selector:
    app: frontend
  type: LoadBalancer
