backend:
  image:
    repository: gitlab.praktikum-services.ru:5050/00_burunov_m/momo-store/momo-store-backend
    tag: latest
  replicas: 1
  service:
    port: 8081
    targetPort: 8081
  revisionHistoryLimit: 15
  imagePullPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

frontend:
  image:
    repository: gitlab.praktikum-services.ru:5050/00_burunov_m/momo-store/momo-store-frontend
    tag: latest
  replicas: 1
  service:
    port: 80
    targetPort: 80
  revisionHistoryLimit: 15
  imagePullPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  env:
    url: VUE_APP_API_URL
    value1: "https://momo-store.digibi.ru"
    mode: NODE_ENV
    value2: "production"
  fqdn_momo: momo-store.digibi.ru
  fqdn_prometheus: prometheus.digibi.ru
  fqdn_grafana: grafana.digibi.ru
  port_backend: 8081
  port_frontend: 80
  port_grafana: 3000
  port_prometheus: 80
